#!/bin/bash
gcc sh6.c sh6lib.c -o sh6 -g
gcc cmd/myls.c cmd/mylslib.c -o cmd/myls -g
gcc cmd/mypwd.c -o cmd/mypwd -g
gcc cmd/mycat.c -o cmd/mycat -g
gcc cmd/mywho.c -o cmd/mywho -g
gcc cmd/myuptime.c cmd/myuptimelib.c -o cmd/myuptime -g
gcc cmd/mycp.c cmd/mycplib.c -o cmd/mycp -g
